Import neccessary libraries

In [2]:
import pandas as pd 
import numpy as np
import matplotlib as plt

Check current directory

In [9]:
import os
print(os.getcwd())
os.listdir()

/Users/arajlymbakenova/Documents/Kaggle/BreastCancerDatasetAnalysis/general

['basic.ipynb']

Define patient_df for the patient profile dataset, see general info

In [11]:
patient_df = pd.read_csv('../datasets/patient_profiles.csv', delimiter=',')
patient_df.head()

,Patient_ID,Age_at_Diagnosis,Molecular_Subtype,BRCA_Mutation,Tumor_Grade,Initial_Tumor_Size_mm
0,BC-00001,60,Triple-Negative,0,1,15.11
1,BC-00002,53,HER2-Enriched,0,1,11.67
2,BC-00003,62,Luminal A,0,1,44.78
3,BC-00004,73,Luminal A,0,1,11.24
4,BC-00005,52,Luminal A,1,1,12.90

In [12]:
patient_df.columns

Index(['Patient_ID', 'Age_at_Diagnosis', 'Molecular_Subtype', 'BRCA_Mutation',
       'Tumor_Grade', 'Initial_Tumor_Size_mm'],
      dtype='object')

In [13]:
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Patient_ID             2500 non-null   object
 1   Age_at_Diagnosis       2500 non-null   int64
 2   Molecular_Subtype      2500 non-null   object
 3   BRCA_Mutation          2500 non-null   int64
 4   Tumor_Grade            2500 non-null   int64
 5   Initial_Tumor_Size_mm  2500 non-null   float64
dtypes: float64(1), int64(3), object(2)
memory usage: 117.3+ KB

In [14]:
patient_df.describe()

       Age_at_Diagnosis  BRCA_Mutation  Tumor_Grade  Initial_Tumor_Size_mm
count       2500.000000    2500.000000  2500.000000            2500.000000
mean          54.906800       0.120400     2.095600              29.573448
std           11.797872       0.325494     0.688949              20.654814
min           16.000000       0.000000     1.000000               1.020000
25%           47.000000       0.000000     2.000000              14.410000
50%           55.000000       0.000000     2.000000              24.945000
75%           63.000000       0.000000     3.000000              39.780000
max          101.000000       1.000000     3.000000             145.110000